### ISSUE TITLE
acces priavte memebers from another reference class

### ISSUE THREAD

**Issue by agstudy** [wch/R6#59]
Within R6 class, is there any possibility to access a private member outside the class or at least from another R6 class?

**Comment by wch** [comment]
No, sorry. Private members can only be accessed within the class or a subclass.

**Comment by piccolbo** [comment]
Don't want to reopen this necessarily, but I was wondering if there is a recommended practice for these use cases:

- two classes working in close coordination, which access each other private members which the end-user should never see or change for that matter (maybe not the best design, but I am working from existing code)
- writing a method for a generic that calls into a class method. In this case I can leave the class method public, since it performs the same operation as the generic, but it can be confusing for the user to have two ways to do the same thing, one advertised and one not so much.

I think it's a feature of R6 to seriously enforce information hiding. Not asking to weaken this guarantee. I just would like to compare notes with other people facing these problems. C++ for instance has the notion of friend functions and classes to selectively bypass information hiding. What should we do in R6?

**Comment by wch** [comment]
For the first, I don't know of a good solution offhand. For the second, I've been considering adding static (or class) methods: #66.

**Comment by piccolbo** [comment]
Got it, thanks. I think you are on the right track by making private members really, strongly private, not wishy washy private.
